[package]
name = "rco"
version = "0.1.3"
authors = ["Theo Henson <theodorehenson@protonmail.com>"]
edition = "2018"

[dependencies]
# For help with parsing csv files
csv = "1.1"

# For easily getting the .config directory path
dirs = "2.0"

# To easily print colored text
colored = "1.9"
